version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.huggingface
    ports:
      - "3080:3080"
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./images:/app/client/public/images
      - ./logs:/app/api/logs